apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2020-09-09T13:18:35Z
  generateName: hello-nginx-6c7d975c9b-
  labels:
    app: hello-nginx
  name: hello-nginx-6c7d975c9b-hv9ns
  namespace: test
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  serviceAccount: default
  terminationGracePeriodSeconds: 30
